services:

  baby-sleep-coach:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "0.0.0.0:${PORT}:80"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8001:8001"
    env_file:
      - .env
    volumes:
      - type: bind
        # You need to update this to absolute path of this dir on your machine
        source: C:\Users\caleb\projects\github-sleepy-baby\BabySleepCoach\
        target: "${APP_DIR}"
    container_name: baby-sleep-coach