services:

  baby-sleep-coach:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "0.0.0.0:${PORT}:80"
      - "0.0.0.0:8000:8000"
      - "0.0.0.0:8001:8001"
    env_file:
      - .env
    volumes:
      - .:/usr/app/babysleepcoach
      - /usr/app/babysleepcoach/webapp/node_modules
    # To use a webcam, uncomment these lines
    # devices:
    #   - /dev/video0
